### ISSUE TITLE
Does not seem to work for mac

### ISSUE THREAD

**Issue by bean5** [mprpic/git-spell-check#1]
I get this error when I try to make a commit:

```
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
```

I installed aspell, which I assume is the only dependency.

**Comment by mprpic** [comment]
Seems that the `mktemp` utility shipped on Mac OS does not support some of the options offered by its Linux counterpart. This question suggests an alternative: https://unix.stackexchange.com/a/84980/18724.

I don't have a Mac that I could test this on so perhaps you could try using the suggested command in place of the current one (lines 51 and 29) to see if it works. Feel free to submit a Pull Request if it does ;-)
